#!/usr/bin/python
#
# Python scripts
Import('env')

# Check the objs
objs = []
objs.append(env.SConscript(['detail/SConscript']))
objs.append(env.SharedObject(Glob('*.cpp')))

# Return
Return('objs')

